### ISSUE TITLE
Project feedback

### ISSUE THREAD

**Issue by renuka-srishti** [airavata-courses/SuperNova#101]
Nice work on Napkin diagram. Can you please share how you design it?

Thanks,
Team Viyad

**Comment by renuka-srishti** [comment]
Also, I tried weather-radar-gateway-app and user-api-app. Running fine.
Good work on service design too.

Thanks,
Team Viyad

**Comment by sanket1211996** [comment]
Thanks you so much follow developers for taking time to review and give your valuable suggestions.
