### ISSUE TITLE
Feedback on Project-1

### ISSUE THREAD

**Issue by vikrantdeshpande09876** [airavata-courses/SuperNova#102]
Hi Team SuperNova,
I went through the installation steps listed [here](https://github.com/airavata-courses/SuperNova/wiki/Weather-Radar-Project-Setup).
Runs fine but I feel these steps could be automated using a shell-script or bat file just to make it easier for a tester/user.

1. I faced errors in step 9.2 and step 11.2 because the Dockerfile in both microservices had: `COPY package*.json /app` instead of `COPY package*.json /app`**/** .

2. All containers seem to be up, but there is no image being generated, maybe you could take a look if there's something going wrong here?

![image](https://user-images.githubusercontent.com/32123572/153322622-83814351-9fb5-4d1a-9d26-bdb6792243e9.png)

![image](https://user-images.githubusercontent.com/32123572/153322530-7df51ade-b378-444e-9044-db8246389f37.png)

The overall user-experience was great though, and the authentication & audit logs seem to be working as expected! 💯 

Best,
Team Scapsulators

**Comment by sanket1211996** [comment]
Thanks for the reviewing and giving through feedback, I will once go through the mentioned points.

**Comment by sanket1211996** [comment]
@vikrantdeshpande09876 Thanks again for taking time for reviewing our project. we have reviewed the setup manual again and didn't find any issue with the either the Dockerfile changes you mentioned- it works perfectly fine, also with the image generation. I think the changes in path you made could have lead to non-generation on image. If you try again, let me know if you face any issue.
