### ISSUE TITLE
Project Feedback: Peer Review

### ISSUE THREAD

**Issue by saiprasad-rane** [airavata-courses/SuperNova#103]
The entire project work has been described precisely with the proper use of Napkin Diagram, architecture diagram and wireframe. I  found Napkin Diagram very interesting and innovative.

I was able to follow the steps mentioned in the documentation properly and each and every services were running properly.

Thanks,
Team Viyad

**Comment by sanket1211996** [comment]
Thanks you so much guyz.

**Comment by sanket1211996** [comment]
Thanks you so much follow developers for taking time to review and give your valuable suggestions.
