### ISSUE TITLE
MSG-MERRA-Api

### ISSUE THREAD

**Issue by sumedhsalvi** [airavata-courses/SuperNova#157]

**Comment by sanket1211996** [comment]
kafka msg outgoing format:
{
    "data_type": "NexRAD",
    "radar_id": "KIND",
    "date": "03-10-2022",
    "plot_data":"xyz"
}

**Comment by sanket1211996** [comment]
incoming format:
{
    "data_type": "NexRAD",
    "radar_id": "KIND",
    "date": "03-10-2022"
}

**Comment by sanket1211996** [comment]
{
    "data_type": "Merra-2",
    "radar_id": "KIND",
    "date": "03-10-2022"
}
